export const GET_ARTICLE = 'GET_ARTICLE';
export const POST_ARTICLE = 'POST_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';

export const REQUEST_START = 'REQUEST_START';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_ERROR = 'REQUEST_ERROR';

export const SHOW_POPUP = 'SHOW_POPUP';
export const CANCEL_POPUP = 'CANCEL_POPUP';
